package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * AlumnoDTO generated by hbm2java
 */
public class AlumnoDTO implements java.io.Serializable {

	private int idAlumno;
	private CarreraDTO carreraDTO;
	private UsuarioDTO usuarioDTO;
	private PersonaDTO personaDTO;
	private String descAlumno;
	private Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs = new HashSet<InscripcionAlumnoDTO>(
			0);

	public AlumnoDTO() {
	}

	public AlumnoDTO(CarreraDTO carreraDTO, UsuarioDTO usuarioDTO,
			PersonaDTO personaDTO) {
		this.carreraDTO = carreraDTO;
		this.usuarioDTO = usuarioDTO;
		this.personaDTO = personaDTO;
	}

	public AlumnoDTO(CarreraDTO carreraDTO, UsuarioDTO usuarioDTO,
			PersonaDTO personaDTO, String descAlumno,
			Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs) {
		this.carreraDTO = carreraDTO;
		this.usuarioDTO = usuarioDTO;
		this.personaDTO = personaDTO;
		this.descAlumno = descAlumno;
		this.inscripcionAlumnoDTOs = inscripcionAlumnoDTOs;
	}

	public int getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(int idAlumno) {
		this.idAlumno = idAlumno;
	}

	public CarreraDTO getCarreraDTO() {
		return this.carreraDTO;
	}

	public void setCarreraDTO(CarreraDTO carreraDTO) {
		this.carreraDTO = carreraDTO;
	}

	public UsuarioDTO getUsuarioDTO() {
		return this.usuarioDTO;
	}

	public void setUsuarioDTO(UsuarioDTO usuarioDTO) {
		this.usuarioDTO = usuarioDTO;
	}

	public PersonaDTO getPersonaDTO() {
		return this.personaDTO;
	}

	public void setPersonaDTO(PersonaDTO personaDTO) {
		this.personaDTO = personaDTO;
	}

	public String getDescAlumno() {
		return this.descAlumno;
	}

	public void setDescAlumno(String descAlumno) {
		this.descAlumno = descAlumno;
	}

	public Set<InscripcionAlumnoDTO> getInscripcionAlumnoDTOs() {
		return this.inscripcionAlumnoDTOs;
	}

	public void setInscripcionAlumnoDTOs(
			Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs) {
		this.inscripcionAlumnoDTOs = inscripcionAlumnoDTOs;
	}

}
