package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * AlumnoDTO generated by hbm2java
 */
public class AlumnoDTO implements java.io.Serializable {

	private int idAlumno;
	private CarreraDTO carreraDTO;
	private UsuarioDTO usuarioDTO;
	private PersonaDTO personaDTO;
	private String descAlumno;
	private Set<InscripcionDTO> inscripcionDTOs = new HashSet<InscripcionDTO>(0);

	public AlumnoDTO() {
	}

	public AlumnoDTO(CarreraDTO carreraDTO, UsuarioDTO usuarioDTO,
			PersonaDTO personaDTO) {
		this.carreraDTO = carreraDTO;
		this.usuarioDTO = usuarioDTO;
		this.personaDTO = personaDTO;
	}

	public AlumnoDTO(CarreraDTO carreraDTO, UsuarioDTO usuarioDTO,
			PersonaDTO personaDTO, String descAlumno,
			Set<InscripcionDTO> inscripcionDTOs) {
		this.carreraDTO = carreraDTO;
		this.usuarioDTO = usuarioDTO;
		this.personaDTO = personaDTO;
		this.descAlumno = descAlumno;
		this.inscripcionDTOs = inscripcionDTOs;
	}

	public int getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(int idAlumno) {
		this.idAlumno = idAlumno;
	}

	public CarreraDTO getCarreraDTO() {
		return this.carreraDTO;
	}

	public void setCarreraDTO(CarreraDTO carreraDTO) {
		this.carreraDTO = carreraDTO;
	}

	public UsuarioDTO getUsuarioDTO() {
		return this.usuarioDTO;
	}

	public void setUsuarioDTO(UsuarioDTO usuarioDTO) {
		this.usuarioDTO = usuarioDTO;
	}

	public PersonaDTO getPersonaDTO() {
		return this.personaDTO;
	}

	public void setPersonaDTO(PersonaDTO personaDTO) {
		this.personaDTO = personaDTO;
	}

	public String getDescAlumno() {
		return this.descAlumno;
	}

	public void setDescAlumno(String descAlumno) {
		this.descAlumno = descAlumno;
	}

	public Set<InscripcionDTO> getInscripcionDTOs() {
		return this.inscripcionDTOs;
	}

	public void setInscripcionDTOs(Set<InscripcionDTO> inscripcionDTOs) {
		this.inscripcionDTOs = inscripcionDTOs;
	}

}
