package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

/**
 * AsistenciaDTO generated by hbm2java
 */
public class AsistenciaDTO implements java.io.Serializable {

	private int idAsistencia;
	private CursoCompuestoDTO cursoCompuestoDTO;
	private PersonaDTO personaDTO;
	private PeriodoDTO periodoDTO;
	private String fechaAsistencia;

	public AsistenciaDTO() {
	}

	public AsistenciaDTO(CursoCompuestoDTO cursoCompuestoDTO,
			PersonaDTO personaDTO, PeriodoDTO periodoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.personaDTO = personaDTO;
		this.periodoDTO = periodoDTO;
	}

	public AsistenciaDTO(CursoCompuestoDTO cursoCompuestoDTO,
			PersonaDTO personaDTO, PeriodoDTO periodoDTO, String fechaAsistencia) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.personaDTO = personaDTO;
		this.periodoDTO = periodoDTO;
		this.fechaAsistencia = fechaAsistencia;
	}

	public int getIdAsistencia() {
		return this.idAsistencia;
	}

	public void setIdAsistencia(int idAsistencia) {
		this.idAsistencia = idAsistencia;
	}

	public CursoCompuestoDTO getCursoCompuestoDTO() {
		return this.cursoCompuestoDTO;
	}

	public void setCursoCompuestoDTO(CursoCompuestoDTO cursoCompuestoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
	}

	public PersonaDTO getPersonaDTO() {
		return this.personaDTO;
	}

	public void setPersonaDTO(PersonaDTO personaDTO) {
		this.personaDTO = personaDTO;
	}

	public PeriodoDTO getPeriodoDTO() {
		return this.periodoDTO;
	}

	public void setPeriodoDTO(PeriodoDTO periodoDTO) {
		this.periodoDTO = periodoDTO;
	}

	public String getFechaAsistencia() {
		return this.fechaAsistencia;
	}

	public void setFechaAsistencia(String fechaAsistencia) {
		this.fechaAsistencia = fechaAsistencia;
	}

}
