package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * AulaDTO generated by hbm2java
 */
public class AulaDTO implements java.io.Serializable {

	private int idAula;
	private String numAula;
	private Set<HorarioDTO> horarioDTOs = new HashSet<HorarioDTO>(0);

	public AulaDTO() {
	}

	public AulaDTO(String numAula, Set<HorarioDTO> horarioDTOs) {
		this.numAula = numAula;
		this.horarioDTOs = horarioDTOs;
	}

	public int getIdAula() {
		return this.idAula;
	}

	public void setIdAula(int idAula) {
		this.idAula = idAula;
	}

	public String getNumAula() {
		return this.numAula;
	}

	public void setNumAula(String numAula) {
		this.numAula = numAula;
	}

	public Set<HorarioDTO> getHorarioDTOs() {
		return this.horarioDTOs;
	}

	public void setHorarioDTOs(Set<HorarioDTO> horarioDTOs) {
		this.horarioDTOs = horarioDTOs;
	}

}
