package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CarreraDTO generated by hbm2java
 */
public class CarreraDTO implements java.io.Serializable {

	private int idCarrera;
	private String desCarrera;
	private Set<AlumnoDTO> alumnoDTOs = new HashSet<AlumnoDTO>(0);
	private Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs = new HashSet<DetalleCursoCarreraCicloDTO>(
			0);

	public CarreraDTO() {
	}

	public CarreraDTO(String desCarrera, Set<AlumnoDTO> alumnoDTOs,
			Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs) {
		this.desCarrera = desCarrera;
		this.alumnoDTOs = alumnoDTOs;
		this.detalleCursoCarreraCicloDTOs = detalleCursoCarreraCicloDTOs;
	}

	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	public String getDesCarrera() {
		return this.desCarrera;
	}

	public void setDesCarrera(String desCarrera) {
		this.desCarrera = desCarrera;
	}

	public Set<AlumnoDTO> getAlumnoDTOs() {
		return this.alumnoDTOs;
	}

	public void setAlumnoDTOs(Set<AlumnoDTO> alumnoDTOs) {
		this.alumnoDTOs = alumnoDTOs;
	}

	public Set<DetalleCursoCarreraCicloDTO> getDetalleCursoCarreraCicloDTOs() {
		return this.detalleCursoCarreraCicloDTOs;
	}

	public void setDetalleCursoCarreraCicloDTOs(
			Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs) {
		this.detalleCursoCarreraCicloDTOs = detalleCursoCarreraCicloDTOs;
	}

}
