package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaCursoDTO generated by hbm2java
 */
public class CategoriaCursoDTO implements java.io.Serializable {

	private int idCategoriaCurso;
	private String descTipoCurso;
	private Set<CursoDTO> cursoDTOs = new HashSet<CursoDTO>(0);

	public CategoriaCursoDTO() {
	}

	public CategoriaCursoDTO(String descTipoCurso, Set<CursoDTO> cursoDTOs) {
		this.descTipoCurso = descTipoCurso;
		this.cursoDTOs = cursoDTOs;
	}

	public int getIdCategoriaCurso() {
		return this.idCategoriaCurso;
	}

	public void setIdCategoriaCurso(int idCategoriaCurso) {
		this.idCategoriaCurso = idCategoriaCurso;
	}

	public String getDescTipoCurso() {
		return this.descTipoCurso;
	}

	public void setDescTipoCurso(String descTipoCurso) {
		this.descTipoCurso = descTipoCurso;
	}

	public Set<CursoDTO> getCursoDTOs() {
		return this.cursoDTOs;
	}

	public void setCursoDTOs(Set<CursoDTO> cursoDTOs) {
		this.cursoDTOs = cursoDTOs;
	}

}
