package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CicloDTO generated by hbm2java
 */
public class CicloDTO implements java.io.Serializable {

	private int idCiclo;
	private String creditosDispon;
	private Set<InscripcionDTO> inscripcionDTOs = new HashSet<InscripcionDTO>(0);
	private Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs = new HashSet<DetalleCursoCarreraCicloDTO>(
			0);

	public CicloDTO() {
	}

	public CicloDTO(String creditosDispon, Set<InscripcionDTO> inscripcionDTOs,
			Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs) {
		this.creditosDispon = creditosDispon;
		this.inscripcionDTOs = inscripcionDTOs;
		this.detalleCursoCarreraCicloDTOs = detalleCursoCarreraCicloDTOs;
	}

	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getCreditosDispon() {
		return this.creditosDispon;
	}

	public void setCreditosDispon(String creditosDispon) {
		this.creditosDispon = creditosDispon;
	}

	public Set<InscripcionDTO> getInscripcionDTOs() {
		return this.inscripcionDTOs;
	}

	public void setInscripcionDTOs(Set<InscripcionDTO> inscripcionDTOs) {
		this.inscripcionDTOs = inscripcionDTOs;
	}

	public Set<DetalleCursoCarreraCicloDTO> getDetalleCursoCarreraCicloDTOs() {
		return this.detalleCursoCarreraCicloDTOs;
	}

	public void setDetalleCursoCarreraCicloDTOs(
			Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs) {
		this.detalleCursoCarreraCicloDTOs = detalleCursoCarreraCicloDTOs;
	}

}
