package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CicloDTO generated by hbm2java
 */
public class CicloDTO implements java.io.Serializable {

	private int idCiclo;
	private String creditosDispon;
	private Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs = new HashSet<InscripcionAlumnoDTO>(
			0);
	private Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs = new HashSet<DetalleCursoCarreraCicloDTO>(
			0);

	public CicloDTO() {
	}

	public CicloDTO(String creditosDispon,
			Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs,
			Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs) {
		this.creditosDispon = creditosDispon;
		this.inscripcionAlumnoDTOs = inscripcionAlumnoDTOs;
		this.detalleCursoCarreraCicloDTOs = detalleCursoCarreraCicloDTOs;
	}

	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getCreditosDispon() {
		return this.creditosDispon;
	}

	public void setCreditosDispon(String creditosDispon) {
		this.creditosDispon = creditosDispon;
	}

	public Set<InscripcionAlumnoDTO> getInscripcionAlumnoDTOs() {
		return this.inscripcionAlumnoDTOs;
	}

	public void setInscripcionAlumnoDTOs(
			Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs) {
		this.inscripcionAlumnoDTOs = inscripcionAlumnoDTOs;
	}

	public Set<DetalleCursoCarreraCicloDTO> getDetalleCursoCarreraCicloDTOs() {
		return this.detalleCursoCarreraCicloDTOs;
	}

	public void setDetalleCursoCarreraCicloDTOs(
			Set<DetalleCursoCarreraCicloDTO> detalleCursoCarreraCicloDTOs) {
		this.detalleCursoCarreraCicloDTOs = detalleCursoCarreraCicloDTOs;
	}

}
