package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CursoCompuestoDTO generated by hbm2java
 */
public class CursoCompuestoDTO implements java.io.Serializable {

	private int idCursoCompuesto;
	private ProfesorDTO profesorDTO;
	private CursoDTO cursoDTO;
	private SeccionDTO seccionDTO;
	private PeriodoDTO periodoDTO;
	private double notaEncuesta;
	private Integer limiteEstudiantes;
	private Set<NotaDTO> notaDTOs = new HashSet<NotaDTO>(0);
	private Set<HorarioDTO> horarioDTOs = new HashSet<HorarioDTO>(0);
	private Set<DetalleInscriCursoDTO> detalleInscriCursoDTOs = new HashSet<DetalleInscriCursoDTO>(
			0);
	private Set<AsistenciaDTO> asistenciaDTOs = new HashSet<AsistenciaDTO>(0);

	public CursoCompuestoDTO() {
	}

	public CursoCompuestoDTO(ProfesorDTO profesorDTO, CursoDTO cursoDTO,
			SeccionDTO seccionDTO, PeriodoDTO periodoDTO) {
		this.profesorDTO = profesorDTO;
		this.cursoDTO = cursoDTO;
		this.seccionDTO = seccionDTO;
		this.periodoDTO = periodoDTO;
	}

	public CursoCompuestoDTO(ProfesorDTO profesorDTO, CursoDTO cursoDTO,
			SeccionDTO seccionDTO, PeriodoDTO periodoDTO, double notaEncuesta,
			Integer limiteEstudiantes, Set<NotaDTO> notaDTOs,
			Set<HorarioDTO> horarioDTOs,
			Set<DetalleInscriCursoDTO> detalleInscriCursoDTOs,
			Set<AsistenciaDTO> asistenciaDTOs) {
		this.profesorDTO = profesorDTO;
		this.cursoDTO = cursoDTO;
		this.seccionDTO = seccionDTO;
		this.periodoDTO = periodoDTO;
		this.notaEncuesta = notaEncuesta;
		this.limiteEstudiantes = limiteEstudiantes;
		this.notaDTOs = notaDTOs;
		this.horarioDTOs = horarioDTOs;
		this.detalleInscriCursoDTOs = detalleInscriCursoDTOs;
		this.asistenciaDTOs = asistenciaDTOs;
	}

	public int getIdCursoCompuesto() {
		return this.idCursoCompuesto;
	}

	public void setIdCursoCompuesto(int idCursoCompuesto) {
		this.idCursoCompuesto = idCursoCompuesto;
	}

	public ProfesorDTO getProfesorDTO() {
		return this.profesorDTO;
	}

	public void setProfesorDTO(ProfesorDTO profesorDTO) {
		this.profesorDTO = profesorDTO;
	}

	public CursoDTO getCursoDTO() {
		return this.cursoDTO;
	}

	public void setCursoDTO(CursoDTO cursoDTO) {
		this.cursoDTO = cursoDTO;
	}

	public SeccionDTO getSeccionDTO() {
		return this.seccionDTO;
	}

	public void setSeccionDTO(SeccionDTO seccionDTO) {
		this.seccionDTO = seccionDTO;
	}

	public PeriodoDTO getPeriodoDTO() {
		return this.periodoDTO;
	}

	public void setPeriodoDTO(PeriodoDTO periodoDTO) {
		this.periodoDTO = periodoDTO;
	}

	public double getNotaEncuesta() {
		return this.notaEncuesta;
	}

	public void setNotaEncuesta(double notaEncuesta) {
		this.notaEncuesta = notaEncuesta;
	}

	public Integer getLimiteEstudiantes() {
		return this.limiteEstudiantes;
	}

	public void setLimiteEstudiantes(Integer limiteEstudiantes) {
		this.limiteEstudiantes = limiteEstudiantes;
	}

	public Set<NotaDTO> getNotaDTOs() {
		return this.notaDTOs;
	}

	public void setNotaDTOs(Set<NotaDTO> notaDTOs) {
		this.notaDTOs = notaDTOs;
	}

	public Set<HorarioDTO> getHorarioDTOs() {
		return this.horarioDTOs;
	}

	public void setHorarioDTOs(Set<HorarioDTO> horarioDTOs) {
		this.horarioDTOs = horarioDTOs;
	}

	public Set<DetalleInscriCursoDTO> getDetalleInscriCursoDTOs() {
		return this.detalleInscriCursoDTOs;
	}

	public void setDetalleInscriCursoDTOs(
			Set<DetalleInscriCursoDTO> detalleInscriCursoDTOs) {
		this.detalleInscriCursoDTOs = detalleInscriCursoDTOs;
	}

	public Set<AsistenciaDTO> getAsistenciaDTOs() {
		return this.asistenciaDTOs;
	}

	public void setAsistenciaDTOs(Set<AsistenciaDTO> asistenciaDTOs) {
		this.asistenciaDTOs = asistenciaDTOs;
	}

}
