package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

/**
 * DetalleCursoCarreraCicloDTOId generated by hbm2java
 */
public class DetalleCursoCarreraCicloDTOId implements java.io.Serializable {

	private int idCiclo;
	private int idCarrera;
	private int idCurso;

	public DetalleCursoCarreraCicloDTOId() {
	}

	public DetalleCursoCarreraCicloDTOId(int idCiclo, int idCarrera, int idCurso) {
		this.idCiclo = idCiclo;
		this.idCarrera = idCarrera;
		this.idCurso = idCurso;
	}

	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	public int getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(int idCurso) {
		this.idCurso = idCurso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetalleCursoCarreraCicloDTOId))
			return false;
		DetalleCursoCarreraCicloDTOId castOther = (DetalleCursoCarreraCicloDTOId) other;

		return (this.getIdCiclo() == castOther.getIdCiclo())
				&& (this.getIdCarrera() == castOther.getIdCarrera())
				&& (this.getIdCurso() == castOther.getIdCurso());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCiclo();
		result = 37 * result + this.getIdCarrera();
		result = 37 * result + this.getIdCurso();
		return result;
	}

}
