package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

/**
 * DetalleInscriCursoDTO generated by hbm2java
 */
public class DetalleInscriCursoDTO implements java.io.Serializable {

	private CursoCompuestoDTO cursoCompuestoDTO;
	private InscripcionDTO inscripcionDTO;
	private double promedioC;

	public DetalleInscriCursoDTO() {
	}

	public DetalleInscriCursoDTO(CursoCompuestoDTO cursoCompuestoDTO, InscripcionDTO inscripcionDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.inscripcionDTO = inscripcionDTO;
	}

	public DetalleInscriCursoDTO(CursoCompuestoDTO cursoCompuestoDTO, InscripcionDTO inscripcionDTO,
			double promedioC) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.inscripcionDTO = inscripcionDTO;
		this.promedioC = promedioC;
	}

	public CursoCompuestoDTO getCursoCompuestoDTO() {
		return this.cursoCompuestoDTO;
	}

	public void setCursoCompuestoDTO(CursoCompuestoDTO cursoCompuestoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
	}

	public InscripcionDTO getInscripcionDTO() {
		return this.inscripcionDTO;
	}

	public void setInscripcionDTO(InscripcionDTO inscripcionDTO) {
		this.inscripcionDTO = inscripcionDTO;
	}

	public double getPromedioC() {
		return this.promedioC;
	}

	public void setPromedioC(double promedioC) {
		this.promedioC = promedioC;
	}

}
