package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

/**
 * DetalleInscriCursoDTO generated by hbm2java
 */
public class DetalleInscriCursoDTO implements java.io.Serializable {

	private CursoCompuestoDTO cursoCompuestoDTO;
	private InscripcionAlumnoDTO inscripcionAlumnoDTO;
	private double promedioC;

	public DetalleInscriCursoDTO() {
	}

	public DetalleInscriCursoDTO(CursoCompuestoDTO cursoCompuestoDTO,
			InscripcionAlumnoDTO inscripcionAlumnoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.inscripcionAlumnoDTO = inscripcionAlumnoDTO;
	}

	public DetalleInscriCursoDTO(CursoCompuestoDTO cursoCompuestoDTO,
			InscripcionAlumnoDTO inscripcionAlumnoDTO, double promedioC) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.inscripcionAlumnoDTO = inscripcionAlumnoDTO;
		this.promedioC = promedioC;
	}
	public CursoCompuestoDTO getCursoCompuestoDTO() {
		return this.cursoCompuestoDTO;
	}

	public void setCursoCompuestoDTO(CursoCompuestoDTO cursoCompuestoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
	}

	public InscripcionAlumnoDTO getInscripcionAlumnoDTO() {
		return this.inscripcionAlumnoDTO;
	}

	public void setInscripcionAlumnoDTO(
			InscripcionAlumnoDTO inscripcionAlumnoDTO) {
		this.inscripcionAlumnoDTO = inscripcionAlumnoDTO;
	}

	public double getPromedioC() {
		return this.promedioC;
	}

	public void setPromedioC(double promedioC) {
		this.promedioC = promedioC;
	}

}
