package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

/**
 * DetalleInscriCursoDTOId generated by hbm2java
 */
public class DetalleInscriCursoDTOId implements java.io.Serializable {

	private int idInscripcion;
	private int idCursoCompuesto;

	public DetalleInscriCursoDTOId() {
	}

	public DetalleInscriCursoDTOId(int idInscripcion, int idCursoCompuesto) {
		this.idInscripcion = idInscripcion;
		this.idCursoCompuesto = idCursoCompuesto;
	}

	public int getIdInscripcion() {
		return this.idInscripcion;
	}

	public void setIdInscripcion(int idInscripcion) {
		this.idInscripcion = idInscripcion;
	}

	public int getIdCursoCompuesto() {
		return this.idCursoCompuesto;
	}

	public void setIdCursoCompuesto(int idCursoCompuesto) {
		this.idCursoCompuesto = idCursoCompuesto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetalleInscriCursoDTOId))
			return false;
		DetalleInscriCursoDTOId castOther = (DetalleInscriCursoDTOId) other;

		return (this.getIdInscripcion() == castOther.getIdInscripcion())
				&& (this.getIdCursoCompuesto() == castOther
						.getIdCursoCompuesto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdInscripcion();
		result = 37 * result + this.getIdCursoCompuesto();
		return result;
	}

}
