package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

/**
 * DetalleCursoCarreraCicloDTO generated by hbm2java
 */
public class DetalleCursoCarreraCicloDTO implements java.io.Serializable {

	private DetalleCursoCarreraCicloDTOId id;
	private CicloDTO cicloDTO;
	private CursoDTO cursoDTO;
	private CarreraDTO carreraDTO;

	public DetalleCursoCarreraCicloDTO() {
	}

	public DetalleCursoCarreraCicloDTO(DetalleCursoCarreraCicloDTOId id,
			CicloDTO cicloDTO, CursoDTO cursoDTO, CarreraDTO carreraDTO) {
		this.id = id;
		this.cicloDTO = cicloDTO;
		this.cursoDTO = cursoDTO;
		this.carreraDTO = carreraDTO;
	}

	public DetalleCursoCarreraCicloDTOId getId() {
		return this.id;
	}

	public void setId(DetalleCursoCarreraCicloDTOId id) {
		this.id = id;
	}

	public CicloDTO getCicloDTO() {
		return this.cicloDTO;
	}

	public void setCicloDTO(CicloDTO cicloDTO) {
		this.cicloDTO = cicloDTO;
	}

	public CursoDTO getCursoDTO() {
		return this.cursoDTO;
	}

	public void setCursoDTO(CursoDTO cursoDTO) {
		this.cursoDTO = cursoDTO;
	}

	public CarreraDTO getCarreraDTO() {
		return this.carreraDTO;
	}

	public void setCarreraDTO(CarreraDTO carreraDTO) {
		this.carreraDTO = carreraDTO;
	}

}
