package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

/**
 * DetalleCursoCarreraCicloDTO generated by hbm2java
 */
public class DetalleCursoCarreraCicloDTO implements java.io.Serializable {

	private CicloDTO cicloDTO;
	private CursoDTO cursoDTO;
	private CarreraDTO carreraDTO;

	public DetalleCursoCarreraCicloDTO() {
	}

	public DetalleCursoCarreraCicloDTO(CicloDTO cicloDTO, CursoDTO cursoDTO, CarreraDTO carreraDTO) {
		this.cicloDTO = cicloDTO;
		this.cursoDTO = cursoDTO;
		this.carreraDTO = carreraDTO;
	}

	public CicloDTO getCicloDTO() {
		return this.cicloDTO;
	}

	public void setCicloDTO(CicloDTO cicloDTO) {
		this.cicloDTO = cicloDTO;
	}

	public CursoDTO getCursoDTO() {
		return this.cursoDTO;
	}

	public void setCursoDTO(CursoDTO cursoDTO) {
		this.cursoDTO = cursoDTO;
	}

	public CarreraDTO getCarreraDTO() {
		return this.carreraDTO;
	}

	public void setCarreraDTO(CarreraDTO carreraDTO) {
		this.carreraDTO = carreraDTO;
	}

}
