package com.intranet.bean;

// Generated 10-sep-2013 6:50:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * InscripcionDTO generated by hbm2java
 */
public class InscripcionDTO implements java.io.Serializable {

	private int idInscripcion;
	private CicloDTO cicloDTO;
	private AlumnoDTO alumnoDTO;
	private PeriodoDTO periodoDTO;
	private String fecInscrito;
	private double promedioGenral;
	private int aprobado;
	private Set<NotaDTO> notaDTOs = new HashSet<NotaDTO>(0);
	private Set<DetalleInscriCursoDTO> detalleInscriCursoDTOs = new HashSet<DetalleInscriCursoDTO>(
			0);

	public InscripcionDTO() {
	}

	public InscripcionDTO(CicloDTO cicloDTO, AlumnoDTO alumnoDTO,
			PeriodoDTO periodoDTO) {
		this.cicloDTO = cicloDTO;
		this.alumnoDTO = alumnoDTO;
		this.periodoDTO = periodoDTO;
	}

	public InscripcionDTO(CicloDTO cicloDTO, AlumnoDTO alumnoDTO,
			PeriodoDTO periodoDTO, String fecInscrito, double promedioGenral,
			int aprobado, Set<NotaDTO> notaDTOs,
			Set<DetalleInscriCursoDTO> detalleInscriCursoDTOs) {
		this.cicloDTO = cicloDTO;
		this.alumnoDTO = alumnoDTO;
		this.periodoDTO = periodoDTO;
		this.fecInscrito = fecInscrito;
		this.promedioGenral = promedioGenral;
		this.aprobado = aprobado;
		this.notaDTOs = notaDTOs;
		this.detalleInscriCursoDTOs = detalleInscriCursoDTOs;
	}

	public int getIdInscripcion() {
		return this.idInscripcion;
	}

	public void setIdInscripcion(int idInscripcion) {
		this.idInscripcion = idInscripcion;
	}

	public CicloDTO getCicloDTO() {
		return this.cicloDTO;
	}

	public void setCicloDTO(CicloDTO cicloDTO) {
		this.cicloDTO = cicloDTO;
	}

	public AlumnoDTO getAlumnoDTO() {
		return this.alumnoDTO;
	}

	public void setAlumnoDTO(AlumnoDTO alumnoDTO) {
		this.alumnoDTO = alumnoDTO;
	}

	public PeriodoDTO getPeriodoDTO() {
		return this.periodoDTO;
	}

	public void setPeriodoDTO(PeriodoDTO periodoDTO) {
		this.periodoDTO = periodoDTO;
	}

	public String getFecInscrito() {
		return this.fecInscrito;
	}

	public void setFecInscrito(String fecInscrito) {
		this.fecInscrito = fecInscrito;
	}

	public double getPromedioGenral() {
		return this.promedioGenral;
	}

	public void setPromedioGenral(double promedioGenral) {
		this.promedioGenral = promedioGenral;
	}

	public int getAprobado() {
		return this.aprobado;
	}

	public void setAprobado(int aprobado) {
		this.aprobado = aprobado;
	}

	public Set<NotaDTO> getNotaDTOs() {
		return this.notaDTOs;
	}

	public void setNotaDTOs(Set<NotaDTO> notaDTOs) {
		this.notaDTOs = notaDTOs;
	}

	public Set<DetalleInscriCursoDTO> getDetalleInscriCursoDTOs() {
		return this.detalleInscriCursoDTOs;
	}

	public void setDetalleInscriCursoDTOs(
			Set<DetalleInscriCursoDTO> detalleInscriCursoDTOs) {
		this.detalleInscriCursoDTOs = detalleInscriCursoDTOs;
	}

}
