package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * InscripcionDTO generated by hbm2java
 */
public class InscripcionDTO implements java.io.Serializable {

	private int idInscripcion;
	private PeriodoDTO periodoDTO;
	private String fechaInicio;
	private String fechaCierre;
	private Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs = new HashSet<InscripcionAlumnoDTO>(
			0);

	public InscripcionDTO() {
	}

	public InscripcionDTO(int idInscripcion, PeriodoDTO periodoDTO) {
		this.idInscripcion = idInscripcion;
		this.periodoDTO = periodoDTO;
	}

	public InscripcionDTO(int idInscripcion, PeriodoDTO periodoDTO,
			String fechaInicio, String fechaCierre,
			Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs) {
		this.idInscripcion = idInscripcion;
		this.periodoDTO = periodoDTO;
		this.fechaInicio = fechaInicio;
		this.fechaCierre = fechaCierre;
		this.inscripcionAlumnoDTOs = inscripcionAlumnoDTOs;
	}

	public int getIdInscripcion() {
		return this.idInscripcion;
	}

	public void setIdInscripcion(int idInscripcion) {
		this.idInscripcion = idInscripcion;
	}

	public PeriodoDTO getPeriodoDTO() {
		return this.periodoDTO;
	}

	public void setPeriodoDTO(PeriodoDTO periodoDTO) {
		this.periodoDTO = periodoDTO;
	}

	public String getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(String fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(String fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Set<InscripcionAlumnoDTO> getInscripcionAlumnoDTOs() {
		return this.inscripcionAlumnoDTOs;
	}

	public void setInscripcionAlumnoDTOs(
			Set<InscripcionAlumnoDTO> inscripcionAlumnoDTOs) {
		this.inscripcionAlumnoDTOs = inscripcionAlumnoDTOs;
	}

}
