package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

/**
 * NotaDTO generated by hbm2java
 */
public class NotaDTO implements java.io.Serializable {

	private int idNota;
	private CursoCompuestoDTO cursoCompuestoDTO;
	private PesoNotaDTO pesoNotaDTO;
	private InscripcionAlumnoDTO inscripcionAlumnoDTO;
	private double nota;
	private String fecPublicadoNota;

	public NotaDTO() {
	}

	public NotaDTO(CursoCompuestoDTO cursoCompuestoDTO,
			PesoNotaDTO pesoNotaDTO, InscripcionAlumnoDTO inscripcionAlumnoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.pesoNotaDTO = pesoNotaDTO;
		this.inscripcionAlumnoDTO = inscripcionAlumnoDTO;
	}

	public NotaDTO(CursoCompuestoDTO cursoCompuestoDTO,
			PesoNotaDTO pesoNotaDTO, InscripcionAlumnoDTO inscripcionAlumnoDTO,
			double nota, String fecPublicadoNota) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
		this.pesoNotaDTO = pesoNotaDTO;
		this.inscripcionAlumnoDTO = inscripcionAlumnoDTO;
		this.nota = nota;
		this.fecPublicadoNota = fecPublicadoNota;
	}

	public int getIdNota() {
		return this.idNota;
	}

	public void setIdNota(int idNota) {
		this.idNota = idNota;
	}

	public CursoCompuestoDTO getCursoCompuestoDTO() {
		return this.cursoCompuestoDTO;
	}

	public void setCursoCompuestoDTO(CursoCompuestoDTO cursoCompuestoDTO) {
		this.cursoCompuestoDTO = cursoCompuestoDTO;
	}

	public PesoNotaDTO getPesoNotaDTO() {
		return this.pesoNotaDTO;
	}

	public void setPesoNotaDTO(PesoNotaDTO pesoNotaDTO) {
		this.pesoNotaDTO = pesoNotaDTO;
	}

	public InscripcionAlumnoDTO getInscripcionAlumnoDTO() {
		return this.inscripcionAlumnoDTO;
	}

	public void setInscripcionAlumnoDTO(
			InscripcionAlumnoDTO inscripcionAlumnoDTO) {
		this.inscripcionAlumnoDTO = inscripcionAlumnoDTO;
	}

	public double getNota() {
		return this.nota;
	}

	public void setNota(double nota) {
		this.nota = nota;
	}

	public String getFecPublicadoNota() {
		return this.fecPublicadoNota;
	}

	public void setFecPublicadoNota(String fecPublicadoNota) {
		this.fecPublicadoNota = fecPublicadoNota;
	}

}
