package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PeriodoDTO generated by hbm2java
 */
public class PeriodoDTO implements java.io.Serializable {

	private int idPeriodo;
	private String descPeriodo;
	private Set<InscripcionDTO> inscripcionDTOs = new HashSet<InscripcionDTO>(0);
	private Set<CursoCompuestoDTO> cursoCompuestoDTOs = new HashSet<CursoCompuestoDTO>(
			0);
	private Set<AsistenciaDTO> asistenciaDTOs = new HashSet<AsistenciaDTO>(0);

	public PeriodoDTO() {
	}

	public PeriodoDTO(String descPeriodo, Set<InscripcionDTO> inscripcionDTOs,
			Set<CursoCompuestoDTO> cursoCompuestoDTOs,
			Set<AsistenciaDTO> asistenciaDTOs) {
		this.descPeriodo = descPeriodo;
		this.inscripcionDTOs = inscripcionDTOs;
		this.cursoCompuestoDTOs = cursoCompuestoDTOs;
		this.asistenciaDTOs = asistenciaDTOs;
	}

	public int getIdPeriodo() {
		return this.idPeriodo;
	}

	public void setIdPeriodo(int idPeriodo) {
		this.idPeriodo = idPeriodo;
	}

	public String getDescPeriodo() {
		return this.descPeriodo;
	}

	public void setDescPeriodo(String descPeriodo) {
		this.descPeriodo = descPeriodo;
	}

	public Set<InscripcionDTO> getInscripcionDTOs() {
		return this.inscripcionDTOs;
	}

	public void setInscripcionDTOs(Set<InscripcionDTO> inscripcionDTOs) {
		this.inscripcionDTOs = inscripcionDTOs;
	}

	public Set<CursoCompuestoDTO> getCursoCompuestoDTOs() {
		return this.cursoCompuestoDTOs;
	}

	public void setCursoCompuestoDTOs(Set<CursoCompuestoDTO> cursoCompuestoDTOs) {
		this.cursoCompuestoDTOs = cursoCompuestoDTOs;
	}

	public Set<AsistenciaDTO> getAsistenciaDTOs() {
		return this.asistenciaDTOs;
	}

	public void setAsistenciaDTOs(Set<AsistenciaDTO> asistenciaDTOs) {
		this.asistenciaDTOs = asistenciaDTOs;
	}

}
