package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PersonaDTO generated by hbm2java
 */
public class PersonaDTO implements java.io.Serializable {

	private int idPersona;
	private String nomPersona;
	private String apePersona;
	private int dniPersona;
	private int telfPersona;
	private String direcPersona;
	private byte[] foto;
	private Set<ProfesorDTO> profesorDTOs = new HashSet<ProfesorDTO>(0);
	private Set<AlumnoDTO> alumnoDTOs = new HashSet<AlumnoDTO>(0);

	public PersonaDTO() {
	}

	public PersonaDTO(String nomPersona, String apePersona, int dniPersona,
			int telfPersona, String direcPersona, byte[] foto,
			Set<ProfesorDTO> profesorDTOs, Set<AlumnoDTO> alumnoDTOs) {
		this.nomPersona = nomPersona;
		this.apePersona = apePersona;
		this.dniPersona = dniPersona;
		this.telfPersona = telfPersona;
		this.direcPersona = direcPersona;
		this.foto = foto;
		this.profesorDTOs = profesorDTOs;
		this.alumnoDTOs = alumnoDTOs;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public String getNomPersona() {
		return this.nomPersona;
	}

	public void setNomPersona(String nomPersona) {
		this.nomPersona = nomPersona;
	}

	public String getApePersona() {
		return this.apePersona;
	}

	public void setApePersona(String apePersona) {
		this.apePersona = apePersona;
	}

	public int getDniPersona() {
		return this.dniPersona;
	}

	public void setDniPersona(int dniPersona) {
		this.dniPersona = dniPersona;
	}

	public int getTelfPersona() {
		return this.telfPersona;
	}

	public void setTelfPersona(int telfPersona) {
		this.telfPersona = telfPersona;
	}

	public String getDirecPersona() {
		return this.direcPersona;
	}

	public void setDirecPersona(String direcPersona) {
		this.direcPersona = direcPersona;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public Set<ProfesorDTO> getProfesorDTOs() {
		return this.profesorDTOs;
	}

	public void setProfesorDTOs(Set<ProfesorDTO> profesorDTOs) {
		this.profesorDTOs = profesorDTOs;
	}

	public Set<AlumnoDTO> getAlumnoDTOs() {
		return this.alumnoDTOs;
	}

	public void setAlumnoDTOs(Set<AlumnoDTO> alumnoDTOs) {
		this.alumnoDTOs = alumnoDTOs;
	}

}
