package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * PesoNotaDTO generated by hbm2java
 */
public class PesoNotaDTO implements java.io.Serializable {

	private int idPesoNota;
	private TipoNotaDTO tipoNotaDTO;
	private CursoDTO cursoDTO;
	private double porcentajepesonota;
	private Set<NotaDTO> notaDTOs = new HashSet<NotaDTO>(0);

	public PesoNotaDTO() {
	}

	public PesoNotaDTO(TipoNotaDTO tipoNotaDTO, CursoDTO cursoDTO) {
		this.tipoNotaDTO = tipoNotaDTO;
		this.cursoDTO = cursoDTO;
	}

	public PesoNotaDTO(TipoNotaDTO tipoNotaDTO, CursoDTO cursoDTO,
			double porcentajepesonota, Set<NotaDTO> notaDTOs) {
		this.tipoNotaDTO = tipoNotaDTO;
		this.cursoDTO = cursoDTO;
		this.porcentajepesonota = porcentajepesonota;
		this.notaDTOs = notaDTOs;
	}

	public int getIdPesoNota() {
		return this.idPesoNota;
	}

	public void setIdPesoNota(int idPesoNota) {
		this.idPesoNota = idPesoNota;
	}

	public TipoNotaDTO getTipoNotaDTO() {
		return this.tipoNotaDTO;
	}

	public void setTipoNotaDTO(TipoNotaDTO tipoNotaDTO) {
		this.tipoNotaDTO = tipoNotaDTO;
	}

	public CursoDTO getCursoDTO() {
		return this.cursoDTO;
	}

	public void setCursoDTO(CursoDTO cursoDTO) {
		this.cursoDTO = cursoDTO;
	}

	public double getPorcentajepesonota() {
		return this.porcentajepesonota;
	}

	public void setPorcentajepesonota(double porcentajepesonota) {
		this.porcentajepesonota = porcentajepesonota;
	}

	public Set<NotaDTO> getNotaDTOs() {
		return this.notaDTOs;
	}

	public void setNotaDTOs(Set<NotaDTO> notaDTOs) {
		this.notaDTOs = notaDTOs;
	}

}
