package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SeccionDTO generated by hbm2java
 */
public class SeccionDTO implements java.io.Serializable {

	private int idSeccion;
	private String descSeccion;
	private Set<CursoCompuestoDTO> cursoCompuestoDTOs = new HashSet<CursoCompuestoDTO>(
			0);

	public SeccionDTO() {
	}

	public SeccionDTO(String descSeccion,
			Set<CursoCompuestoDTO> cursoCompuestoDTOs) {
		this.descSeccion = descSeccion;
		this.cursoCompuestoDTOs = cursoCompuestoDTOs;
	}

	public int getIdSeccion() {
		return this.idSeccion;
	}

	public void setIdSeccion(int idSeccion) {
		this.idSeccion = idSeccion;
	}

	public String getDescSeccion() {
		return this.descSeccion;
	}

	public void setDescSeccion(String descSeccion) {
		this.descSeccion = descSeccion;
	}

	public Set<CursoCompuestoDTO> getCursoCompuestoDTOs() {
		return this.cursoCompuestoDTOs;
	}

	public void setCursoCompuestoDTOs(Set<CursoCompuestoDTO> cursoCompuestoDTOs) {
		this.cursoCompuestoDTOs = cursoCompuestoDTOs;
	}

}
