package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TipoNotaDTO generated by hbm2java
 */
public class TipoNotaDTO implements java.io.Serializable {

	private int idTipoNota;
	private String descTipoNota;
	private Set<PesoNotaDTO> pesoNotaDTOs = new HashSet<PesoNotaDTO>(0);

	public TipoNotaDTO() {
	}

	public TipoNotaDTO(String descTipoNota, Set<PesoNotaDTO> pesoNotaDTOs) {
		this.descTipoNota = descTipoNota;
		this.pesoNotaDTOs = pesoNotaDTOs;
	}

	public int getIdTipoNota() {
		return this.idTipoNota;
	}

	public void setIdTipoNota(int idTipoNota) {
		this.idTipoNota = idTipoNota;
	}

	public String getDescTipoNota() {
		return this.descTipoNota;
	}

	public void setDescTipoNota(String descTipoNota) {
		this.descTipoNota = descTipoNota;
	}

	public Set<PesoNotaDTO> getPesoNotaDTOs() {
		return this.pesoNotaDTOs;
	}

	public void setPesoNotaDTOs(Set<PesoNotaDTO> pesoNotaDTOs) {
		this.pesoNotaDTOs = pesoNotaDTOs;
	}

}
