package com.intranet.bean;

// Generated 14-sep-2013 7:16:37 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioDTO generated by hbm2java
 */
public class UsuarioDTO implements java.io.Serializable {

	private int idUsuario;
	private PerfilDTO perfilDTO;
	private String user;
	private String password;
	private Set<ProfesorDTO> profesorDTOs = new HashSet<ProfesorDTO>(0);
	private Set<AlumnoDTO> alumnoDTOs = new HashSet<AlumnoDTO>(0);

	public UsuarioDTO() {
	}

	public UsuarioDTO(PerfilDTO perfilDTO) {
		this.perfilDTO = perfilDTO;
	}

	public UsuarioDTO(PerfilDTO perfilDTO, String user, String password,
			Set<ProfesorDTO> profesorDTOs, Set<AlumnoDTO> alumnoDTOs) {
		this.perfilDTO = perfilDTO;
		this.user = user;
		this.password = password;
		this.profesorDTOs = profesorDTOs;
		this.alumnoDTOs = alumnoDTOs;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public PerfilDTO getPerfilDTO() {
		return this.perfilDTO;
	}

	public void setPerfilDTO(PerfilDTO perfilDTO) {
		this.perfilDTO = perfilDTO;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<ProfesorDTO> getProfesorDTOs() {
		return this.profesorDTOs;
	}

	public void setProfesorDTOs(Set<ProfesorDTO> profesorDTOs) {
		this.profesorDTOs = profesorDTOs;
	}

	public Set<AlumnoDTO> getAlumnoDTOs() {
		return this.alumnoDTOs;
	}

	public void setAlumnoDTOs(Set<AlumnoDTO> alumnoDTOs) {
		this.alumnoDTOs = alumnoDTOs;
	}

}
